# Setup
title:               Bakeries-R-Us
tagline:             'A bakery supply chain game'
description:         'Bake virtual bread and learn'
url:                 https://bakeries-r-us.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Peter Ajtai
  url:               https://bakeries-r-us.github.io
  email:             peter.ajtai@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Misc
destination: docs/

